### PR TITLE
fix rendering of UTF-8 encoded files with DOS/Amiga fonts

### PR DESCRIPTION
**Pull request by kajott**
Mojibake appeared when using the ASCII viewer with the DOS or Amiga fonts on UTF-8 encoded files.

This commit fixes that by not converting text from `cp437` or `iso-8859-1` to `utf-8` if it's already valid UTF-8.

For details, see https://www.pouet.net/topic.php?which=10189&page=8#c573844.

### CODE REVIEW

**Comment by kusma** [comment]
I'm skeptical of this coming back to bite us.

Amiga fonts with utf-8 encoding isn't a thing. Amigas use amiga encoding, and modern machines don't use amiga fonts. So this seems to me to fix a made up problem.

But it's a bit worse; there's no guarantee that no amiga NFO files aren't valid UTF-8, even if they're not UTF-8 encoded. So this might break rendering of old files.

All together, this sounds like it's really a deadline NFO problem, and should be fixed by issuing a sane NFO instead of patching viewers

**Comment by kusma** [comment]
How on earth is box drawing an  "adversarial example"? It's entirely common in NFO files.

**Comment by kajott** [comment]
Again, the problem is not the `─¬` sequence, the problem is that you'd need a whole file consisting of **only** "accidentally valid" UTF-8 sequences. One single vertical bar followed by a space or end of line, and poof, no UTF-8. One horizontal bar of any kind (including dashed bars with spaces inbetween), and poof, no UTF-8. While there sure are practical combinations of characters that could be misinterpreted as UTF-8, _most can not_, and if _any_ of those non-UTF-8 combinations are present in the file, it's no valid UTF-8.

**Comment by sagamusix** [comment]
As a first step, you could run through the entirety of uploaded files and see if any of them would be mis-detected by KeyJ's suggested changes. Maybe add a `preg_match` to check if any characters in the range 0x80-0xFF are present at all, and if there aren't then never assume UTF-8. That would satisfy kusma's counter-example of an CP437 NFO only using character range 0x00-0x7F including control characters.

**Comment by kusma** [comment]
> As a first step, you could run through the entirety of uploaded files and see if any of them would be mis-detected by KeyJ's suggested changes. Maybe add a preg_match to check if any characters in the range 0x80-0xFF are present at all, and if there aren't then never assume UTF-8. That would satisfy kusma's counter-example of an CP437 NFO only using character range 0x00-0x7F including control characters.

No, I don't think it would. We would still be able to misinterpret files that for instance contains `♪` in CP437.

Besides, running through all existing NFO-files doesn't prove that it wont lead to trouble if some old, not-yet-uploaded prods contains problems like that. There's a lot of old releases that still hasn't made the way to Pouët.

I want to stress the point that this is trying to solve an entirely artificial problem. UTF-8 based systems don't have Amiga fonts. If the UTF-8 encoded results file from Deadline requires Topaz to render correctly, then Deadline has made created this problem all by themselves. Risking breaking other NFO files just doesn't seem like the right thing to do to me.

I'm not saying I'm against making the encoding of the file and the fonts-selection orthogonal if that's done in a reasonably simple and robust way. The approach taken here is simple, but it's not robust. Manually marking things seems error-prone to me.

One alternative option could be to add an "amiga but with utf-8" entry [here](https://github.com/pouetnet/pouet2.0/blob/78bb575f83d8d4e2200ae35e6b265c9662d9d603/include_pouet/pouet-asciiviewer.php#L32). That one seems a bit hard to name in a descriptive way, so if so I would propose "nasty deadline workaround" ;)

Even better would probably be to allow specifying both font and encoding to the page, and fixup the [Amiga default-override](https://github.com/pouetnet/pouet2.0/blob/b7cdefee5fd797f1cd7b54aaf95c7c8a242b062a/prod.php#L456) to also specify the encoding. Bonus points if you also add a similar DOS override. We'd also need some UI to allow switching the encoding as well.

It's not clear to me how to decide what a sane default encoding is for party results, though. UTF-8 is probably the right choice for platform-agnostic parties in recent years, but I'm not really sure what the full heuristic for something like that should look like.

**Pull request closed without merging**
